<?php

namespace GenAI\Routing\Util;

use GenAI\Routing\Route\Definition;

/**
 * Stateless helper that compiles declared routes into plain PHP source — a file
 * that populates a runtime Router with a precompiled route table.
 *
 * Normally you do not call this directly: RouterRegister::dump() / dumpToFile()
 * drive it. Each route is emitted as a $this->register(method, regex, params,
 * handler) call, with the regex already compiled at build time, so the runtime
 * never compiles patterns.
 *
 * Generated output (PHP 5.3-safe) is a self-populating router subclass:
 *
 *   <?php
 *   namespace Cache;
 *   class Router extends \GenAI\Routing\Router {
 *       public function __construct() {
 *           $this->register('GET', '#^/user/(?P<id>[^/]+)$#', array('id'), 'UserController@show');
 *           $this->register('POST', '#^/users$#', array(), 'UserController@create');
 *       }
 *   }
 *   // runtime:  $router = new \Cache\Router();   // ready to match
 *
 * Builds only strings, so it is PHP 5.3-safe.
 *
 * Compatible with PHP 5.3.29.
 */
class RouteDumper
{
    /**
     * Compile a list of routes to PHP source for a populate-the-router file.
     *
     * Routes are sorted by specificity first (static segments rank above
     * placeholders), so a literal route like /products/detail always wins over
     * /products/{name} regardless of the order you declared them. The sort is
     * stable, so equally-specific routes keep their registration order — which
     * is what breaks ties under the runtime's first-match-wins.
     *
     * @param Definition[] $routes Declared routes, in registration order.
     * @return string PHP source, starting with "<?php", returning a Closure.
     */
    public static function dump($routes)
    {
        $routes = self::sortBySpecificity($routes);

        $body = array();
        foreach ($routes as $route) {
            $body[] = self::dumpRoute($route);
        }

        $lines = array();
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'namespace Cache;';
        $lines[] = '';
        $lines[] = '// Generated by GenAI\\Routing\\Util\\RouteDumper - do not edit by hand.';
        $lines[] = '// The compiled router: `new \\Cache\\Router()` is ready to match.';
        $lines[] = '';
        $lines[] = 'class Router extends \\GenAI\\Routing\\Router';
        $lines[] = '{';
        $lines[] = '    public function __construct()';
        $lines[] = '    {';
        if (!empty($body)) {
            $lines[] = implode("\n", $body);
        }
        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Render one `$r->register(...)` call for a route.
     *
     * @param Definition $route
     * @return string
     */
    private static function dumpRoute(Definition $route)
    {
        $method  = var_export($route->getMethod(), true);
        $regex   = var_export($route->getRegex(), true);
        $params  = self::dumpStringList($route->getParamNames());
        $handler = var_export($route->getHandler(), true);

        return '    $this->register(' . $method . ', ' . $regex . ', ' . $params . ', ' . $handler . ');';
    }

    /**
     * Render a list of strings as an inline array() literal.
     *
     * @param string[] $names
     * @return string
     */
    private static function dumpStringList($names)
    {
        $items = array();
        foreach ($names as $name) {
            $items[] = var_export($name, true);
        }

        return 'array(' . implode(', ', $items) . ')';
    }

    /**
     * Order routes most-specific-first, stably.
     *
     * Each route gets a per-segment "tier" key (static '2', constrained/mixed
     * placeholder '1', bare placeholder '0'); routes are then sorted by that key
     * descending, compared left-to-right segment by segment (strcmp, so it is a
     * positional comparison, not numeric). Registration order breaks ties.
     *
     * @param Definition[] $routes
     * @return Definition[] A new list in priority order.
     */
    private static function sortBySpecificity($routes)
    {
        // Decorate with the original index so the sort is stable on any PHP
        // version (we do not rely on usort being stable).
        $decorated = array();
        $index = 0;
        foreach ($routes as $route) {
            $decorated[] = array(
                'key'   => self::specificityKey($route),
                'index' => $index,
                'route' => $route,
            );
            $index++;
        }

        usort($decorated, function ($a, $b) {
            $cmp = strcmp($a['key'], $b['key']);
            if ($cmp !== 0) {
                return -$cmp; // greater key (more specific) comes first
            }

            return $a['index'] - $b['index']; // ties keep registration order
        });

        $sorted = array();
        foreach ($decorated as $item) {
            $sorted[] = $item['route'];
        }

        return $sorted;
    }

    /**
     * Build a per-segment specificity key for a route's pattern, e.g.
     * '/products/detail' -> '22', '/products/{name}' -> '20'.
     *
     * @param Definition $route
     * @return string
     */
    private static function specificityKey(Definition $route)
    {
        $segments = explode('/', trim($route->getPattern(), '/'));
        $key      = '';
        foreach ($segments as $segment) {
            $key .= self::segmentTier($segment);
        }

        return $key;
    }

    /**
     * Specificity tier for one path segment: '2' fully static, '1' a constrained
     * or mixed placeholder (it carries some literal/regex specificity), '0' a
     * bare {placeholder}.
     *
     * @param string $segment
     * @return string
     */
    private static function segmentTier($segment)
    {
        if (strpos($segment, '{') === false) {
            return '2';
        }
        if (preg_match('#^\{[a-zA-Z_][a-zA-Z0-9_]*\}$#', $segment)) {
            return '0';
        }

        return '1';
    }
}
