<?php

// Generated by GenAI\Routing\Util\RouteDumper - do not edit by hand.
// Returns a Closure that populates a GenAI\Routing\Router.
// require this file, then call the Closure with your router.

return function (\GenAI\Routing\Router $r) {
    $r->register('GET', '#^/products/detail$#', array(), 'ProductController@detail');
    $r->register('GET', '#^/user/(?P<id>\\d+)/edit$#', array('id'), 'UserController@edit');
    $r->register('GET', '#^/posts/(?P<slug>[^/]+)/comments/(?P<commentId>[^/]+)$#', array('slug', 'commentId'), 'CommentController@show');
    $r->register('GET', '#^/user/(?P<id>[^/]+)$#', array('id'), 'UserController@show');
    $r->register('DELETE', '#^/user/(?P<id>[^/]+)$#', array('id'), 'UserController@destroy');
    $r->register('GET', '#^/products/(?P<name>[^/]+)$#', array('name'), 'ProductController@show');
    $r->register('GET', '#^/$#', array(), 'IndexController@index');
    $r->register('GET', '#^/users$#', array(), 'UserController@index');
    $r->register('POST', '#^/users$#', array(), 'UserController@create');
    $r->register('GET', '#^/health$#', array(), 'HealthController@ping');
};
