<?php

namespace GenAI\Routing;

/**
 * The route engine — the runtime half.
 *
 * It matches requests against a precompiled route table loaded from the file
 * the RouteDumper wrote; it never compiles patterns itself. Declaring routes is
 * a build-time concern that lives in RouterRegister, not here.
 *
 * Build-time declaration happens elsewhere:
 *
 *   $register = new RouterRegister();
 *   $register->get('/user/{id}', 'UserController@show');
 *   $register->dumpToFile(__DIR__ . '/cache/routes.php');
 *
 * Runtime — load the compiled table, then match:
 *
 *   $router = new Router();
 *   $router->loadCompiled(__DIR__ . '/cache/routes.php');
 *
 *   $m = $router->match('GET', '/user/5');
 *   $m->getHandler();  // 'UserController@show'
 *   $m->getParams();   // array('id' => '5')
 *
 * Compatible with PHP 5.3.29.
 */
class Router
{
    /**
     * Precompiled routes, in registration order (first match wins). Each entry
     * is array('method' => string, 'regex' => string, 'params' => string[],
     * 'handler' => mixed).
     *
     * @var array
     */
    private $routes = array();

    /**
     * Register a precompiled route. This is what the file generated by the
     * RouteDumper calls; you normally never call it by hand.
     *
     * @param string   $method  Upper-cased HTTP method, or '*' for any.
     * @param string   $regex   The compiled matching regex.
     * @param string[] $params  Placeholder names captured by the regex.
     * @param mixed    $handler Whatever to return on a match.
     * @return Router $this, for chaining.
     */
    public function register($method, $regex, array $params, $handler)
    {
        $this->routes[] = array(
            'method'  => strtoupper($method),
            'regex'   => $regex,
            'params'  => $params,
            'handler' => $handler,
        );

        return $this;
    }

    /**
     * Match an incoming request against the registered routes.
     *
     * The first route that matches both the method and the path wins, so
     * register more specific routes before more general ones.
     *
     * @param string $method The request method, e.g. 'GET' (case-insensitive).
     * @param string $path   The request path, e.g. '/user/5'.
     * @return RouteMatch|false RouteMatch on success, false on no match (404).
     */
    public function match($method, $path)
    {
        $method = strtoupper($method);
        $path   = $this->normalize($path);

        foreach ($this->routes as $route) {
            if ($route['method'] !== '*' && $route['method'] !== $method) {
                continue;
            }

            if (!preg_match($route['regex'], $path, $matches)) {
                continue;
            }

            $params = array();
            foreach ($route['params'] as $name) {
                if (isset($matches[$name])) {
                    $params[$name] = $matches[$name];
                }
            }

            return new RouteMatch($route['handler'], $params);
        }

        return false;
    }

    /**
     * Ensure a leading slash and strip any trailing slash (except for root) —
     * the same normalization the patterns were compiled with.
     *
     * @param string $path
     * @return string
     */
    private function normalize($path)
    {
        $path = '/' . ltrim($path, '/');

        if ($path !== '/') {
            $path = rtrim($path, '/');
        }

        return $path;
    }
}
